// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbExKEgedH2LSWblJdVX2VzHLmOYPl0RY',
    appId: '1:690896361290:web:62567d78cd6a31ed3e53b3',
    messagingSenderId: '690896361290',
    projectId: 'tabatatimer-d8d31',
    authDomain: 'tabatatimer-d8d31.firebaseapp.com',
    storageBucket: 'tabatatimer-d8d31.appspot.com',
    measurementId: 'G-VNVYS7MRSM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAutP9qjiRx8cMIj1emxaFSv-dX5yXwrzw',
    appId: '1:690896361290:android:df9a0196de6fe7153e53b3',
    messagingSenderId: '690896361290',
    projectId: 'tabatatimer-d8d31',
    storageBucket: 'tabatatimer-d8d31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsgRYQMILCn99rUZYZbIt9bjTOp_3ytNw',
    appId: '1:690896361290:ios:196a5dbc08f26b7c3e53b3',
    messagingSenderId: '690896361290',
    projectId: 'tabatatimer-d8d31',
    storageBucket: 'tabatatimer-d8d31.appspot.com',
    iosClientId: '690896361290-0k71e9tlbtoiufqtghagsiirf2mf7hu7.apps.googleusercontent.com',
    iosBundleId: 'com.example.tabataTimer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsgRYQMILCn99rUZYZbIt9bjTOp_3ytNw',
    appId: '1:690896361290:ios:86dcb3c17701761e3e53b3',
    messagingSenderId: '690896361290',
    projectId: 'tabatatimer-d8d31',
    storageBucket: 'tabatatimer-d8d31.appspot.com',
    iosClientId: '690896361290-lch0guoi6ij0ae61ngkn0cclvmknhaas.apps.googleusercontent.com',
    iosBundleId: 'com.example.tabataTimer.RunnerTests',
  );
}
